# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0003_auto_20170707_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
