# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0006_auto_20170708_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
