# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0010_auto_20170710_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
