# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0013_auto_20170710_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
    ]
