# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0014_remove_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
