# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0015_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sales_rank',
            field=models.IntegerField(default=0),
        ),
    ]
