# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0016_book_sales_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tech_valley_best',
            field=models.BooleanField(default=False),
        ),
    ]
