# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0017_book_tech_valley_best'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
