# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0018_auto_20170713_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
