# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_useraddress_userdefaultaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorize_net_profile_id',
            field=models.IntegerField(null=True),
        ),
    ]
