# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_userpayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayments',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
